"""empty message

Revision ID: 42120230474
Revises: None
Create Date: 2014-09-01 16:51:05.310473

"""

# revision identifiers, used by Alembic.
revision = '42120230474'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ymci_ext_test_junit__result',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('fail', sa.Integer(), nullable=True),
    sa.Column('error', sa.Integer(), nullable=True),
    sa.Column('skip', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id', 'build_id'], ['build.project_id', 'build.build_id'], ),
    sa.PrimaryKeyConstraint('project_id', 'build_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ymci_ext_test_junit__result')
    ### end Alembic commands ###
